### Numpy Task

In [6]:
import numpy as np

# 1~10까지의 요소를 ndarray에 담는다.
# ndarray1 = np.array(list(range(1, 11)))
ndarray1 = np.arange(start=1, stop=11)
print(ndarray1)

# 3행 2열 list를 ndarray에 담고 각 요소는 순서대로 6, 5, 4, 3, 2, 1이다.
python_list = []
python_list.append([6 - i for i in range(2)])
python_list.append([4 - i for i in range(2)])
python_list.append([2 - i for i in range(2)])

ndarray2 = np.array(python_list)
print(type(ndarray2), ndarray2.shape, ndarray2.ndim, ndarray2.dtype, sep="\n")

# 4행 1열 ndarray, 순서대로 10, 8, 6, 4를 담는다
# Transpose: 전치, 행과 열을 바꿔준다.
ndarray2 = np.array([[(5 - i) * 2 for i in range(4)]]).T
print(ndarray2)

# 1~10까지 요소를 ndarray에 담고 각 요소에 5씩 더해준다.
ndarray1 = np.arange(start=1, stop=11)
ndarray1_oper = ndarray1 + 5
print(ndarray1_oper)

# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32인 ndarray만들기
ndarray1 = np.zeros((10,), dtype=np.int32)
print(ndarray1, ndarray1.shape, sep="\n")

# axis 0이 3, axis1이 4인 shape이면서 모든 원소가 1인 ndarray 만들기
ndarray1 = np.ones((3, 4), dtype=np.int8)
print(ndarray1, ndarray1.shape, sep="\n")

# axis 0이 5, 각 요소가 0~4인 ndarray 만들기
ndarray1 = np.arange(stop=5)
print(ndarray1, ndarray1.shape, sep="\n")

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=0, stop=16)

# 2 Dimension, axis 1은 2로 변경
ndarray2 = ndarray1.reshape((-1, 2))
print(ndarray2, ndarray2.shape, sep="\n")

# 2 Dimension, axis 0은 8로 변경
ndarray2 = ndarray1.reshape((8, -1))
print(ndarray2, ndarray2.shape, sep="\n")

# 3 Dimension으로 변경
ndarray3 = ndarray1.reshape((4, 2, -1))
print(ndarray3, ndarray3.shape, sep="\n")

# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
ndarray2 = ndarray3.reshape((-1, 1))
print(ndarray2, ndarray2.shape, sep="\n")

# ndarray3을 1 Dimension으로 변환
# ndarray1 = ndarray3.reshape((-1, ))
ndarray1 = ndarray3.flatten()
print(ndarray1, ndarray1.shape, sep="\n")

# 1차원 ndarray 1~100까지 값 중 97값 추출하기
ndarray1 = np.arange(start=1, stop=101)
print(ndarray1[96])

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=21)

# 2차원 배열 axis 0은 4, axis 1은 5로 1~20 요소 값 중 15값 추출하기
ndarray2 = ndarray1.reshape((4, 5))
print(ndarray2[2, 4])

# 2 Dimension, axis 0은 5로 변경
ndarray2 = ndarray1.reshape((5, -1))

# 2행의 4번째 숫자 출력
print(ndarray2[1, 3])

# 1~100중 짝수만 출력
ndarray1 = np.arange(start=1, stop=101)
ndarray1_even = ndarray1[ndarray1 % 2 == 0]

# 위에서 구한 짝수들을 axis 0이 10인 2차원 배열로 변환 후 82~100까지 추출
ndarray2_even = ndarray1_even.reshape((10, -1))
ndarray2_even_ex = ndarray2_even[8:]

# 위에서 구한 요소 중 (86, 100) 좌표 구하기
print(ndarray2_even_ex)
print("86의 좌표(x, y): (0, 2)")
print("100의 좌표(x, y): (1, 4)")
print(ndarray2_even_ex[0, 2], ndarray2_even_ex[1, 4])

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=101)

# 각 요소중 1의 자리수가 2인 수들만 추출하기
print(ndarray1[ndarray1 % 10 == 2])

# 1~49요소 중 2와 5의 공배수 추출하기
ndarray1 = np.arange(start=1, stop=50)
condition1 = ndarray1 % 2 == 0
condition2 = ndarray1 % 5 == 0
condition3 = condition1 & condition2
result = ndarray1[condition3]

# 위에서 추출한 공배수 중 20이상인 값만 추출하기
condition = result >= 20
print(result[condition])

# 데이터를 분석하여, 각 수치별 오름차순 및 내림차순 후 이름을 출력하세요.
# [[과일이름], [가격]], 가격별 내림차순
array1 = [['Mango', 'Apple', 'Pear', 'Pitch', 'Melon'], [1500, 1800, 2000, 2500, 8500]]

ndarray2 = np.array(array1)
fruit_name = ndarray2[:1].flatten()
fruit_price = ndarray2[-1]

print(fruit_name, fruit_price, sep="\n")

fruit_name_asc = fruit_name[fruit_price.argsort()[::-1]]
print(fruit_name_asc)

# [[이름], [나이], [학점]], 나이별 내림차순, 학점별 오름차순
array2 = [['둘리', '또치', '길동', '도너', '마이콜'], [7, 9, 40, 5, 20], ['C', 'A', 'B', 'F', 'D']]

ndarray2 = np.array(array2)
names = ndarray2[:1].flatten()
ages = ndarray2[1].astype(np.int16)
grades = ndarray2[-1]

print(names, ages, grades)

print(names[ages.argsort()[::-1]])
print(names[grades.argsort()])

# [[국가이름], [GDP 성장률]], GDP 성장률별 오름차순
array3 = [['한국', '영국', '러시아', '남아프리카 공화국', '미국'], ['1.7%', '-0.6%', '0.3%', '1.2%', '1.4%']]
gdp_list = []
ndarray2 = np.array(array3)

nations = ndarray2[0]
gdps = ndarray2[1]


for gdp in gdps:
    gdp_list.append(gdp.replace('%', ''))

gdps = np.array(gdp_list, dtype=np.float16)

print(nations[gdps.argsort()])

[ 1  2  3  4  5  6  7  8  9 10]
[[6 5]
 [4 3]
 [2 1]]
[[6 5]
 [4 3]
 [2 1]]
[10  8  6  4]
[10  8  6  4]
[ 6  7  8  9 10 11 12 13 14 15]
[ 6  7  8  9 10 11 12 13 14 15]
[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[0 1 2 3 4]
[0 1 2 3 4]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[[ 0]
  [ 1]]

 [[ 2]
  [ 3]]

 [[ 4]
  [ 5]]

 [[ 6]
  [ 7]]

 [[ 8]
  [ 9]]

 [[10]
  [11]]

 [[12]
  [13]]

 [[14]
  [15]]]
[[[ 0]
  [ 1]]

 [[ 2]
  [ 3]]

 [[ 4]
  [ 5]]

 [[ 6]
  [ 7]]

 [[ 8]
  [ 9]]

 [[10]
  [11]]

 [[12]
  [13]]

 [[14]
  [15]]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
